### ISSUE TITLE
Keep Alive 0x00 Unknown Message Type

### ISSUE THREAD

**Issue by AdamBusch** [rakusan2/FRC-NT-Client#6] opened 2018-01-09 05:08 UTC
I keep getting errors when trying to connect to a robot about 50% of the time. 
The error points to the known message list, and the[ 0x00 keep alive message](https://github.com/wpilibsuite/ntcore/blob/master/doc/networktables3.adoc#keep-alive-1) not being one of them (thus throwing this error).

{ buf: <Buffer 00> }
{ con: true,
  err:
   Error: Unknown Message Type - 0x00
       at Client.read (C:\Users\adamj\Development\FRC-6800-2018-code\FRCDashboard\node_modules\wpilib-nt-client\index.js:335:19)
       at Socket.client.on.data (C:\Users\adamj\Development\FRC-6800-2018-code\FRCDashboard\node_modules\wpilib-nt-client\index.js:253:26)
       at emitOne (events.js:96:13)
       at Socket.emit (events.js:191:7)
       at readableAddChunk (_stream_readable.js:178:18)
       at Socket.Readable.push (_stream_readable.js:136:10)
       at TCP.onread (net.js:560:20) }

**Comment by rakusan2** [comment] 2018-01-09 16:21
Sorry about this and thank you for reporting.
The error was caused by me forgetting to accept the keep alive message.
This has been fixed in 1.3.1

**Closed as completed by rakusan2** 2018-01-09 16:21 UTC
